parameters:
#    tangara_svg_editor.example.class: Tangara\SVGEditorBundle\Example

services:
#    tangara_svg_editor.example:
#        class: %tangara_svg_editor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
